---
title: "Jo's Graphics"
output: pdf_document
date: "2023-05-04"
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r, echo=FALSE}
# load packages - add any you would like
library(tidyverse)
library(lme4)
library(lmerTest)
library(gridExtra)
library(knitr)
library(stringr)
library(zoo)
library(GGally)
library(jtools)
library(rsample)
library(broom)   
library(ggformula)
library(MASS) 
library(mnormt) 
library(kableExtra)
library(Hmisc)
library(nlme)
```

```{r, echo=FALSE}
gdp <- read.csv("Table.csv") %>% rename(xState = GeoName)
names(gdp)=str_sub(names(gdp),2)
gdp <- gdp %>% pivot_longer('1997':'2018',names_to = "Year", values_to = "GDP")

unemployment <- read.csv("Copy of emp-unemployment.csv") %>% rename(xState = Area)
names(unemployment)=str_sub(names(unemployment),2)
unemployment <- unemployment %>% pivot_longer('1997':'2018',names_to = "Year", values_to = "Unemployment")

join_1 <- full_join(gdp,unemployment, by=c('State','Year')) %>% dplyr::select(-'eoFips',-c('2019':'2022'),-c('1980':'1996'))

regions <- read.csv("https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv")

join_2 <- right_join(join_1,regions, by='State') %>% dplyr::select(-State.Code)

popest <- read.csv("Popest.csv") %>% rename(xState.00 = State)
names(popest)=str_sub(names(popest),2,-4)
popest <- popest %>% pivot_longer('1997':'2018',names_to = "Year", values_to = "PopEst")

join_3 <- left_join(join_2,popest,by=c('State','Year')) %>% mutate(Year = as.integer(Year))
join_3$gdp_per_capita <- join_3$GDP*10^6/join_3$PopEst

elections <- read.csv("1976-2020-president.csv") %>% 
  filter(year>=1996 & year<=2018) %>%
  group_by(state,year) %>% top_n(1,candidatevotes) %>%
  mutate(party = party_simplified) %>%
  dplyr::select(year,state,party)
  
elections$state = str_to_title(elections$state)
elections$party = str_sub(elections$party,1,1)

ds_years <- data.frame(1996:2018) %>% slice(rep(1:n(), each = 51))
ds_states <- data.frame(unique(elections$state))
ds_states <- as.data.frame(lapply(ds_states,rep,23))

ds_final <- data.frame(ds_years$X1996.2018,ds_states$unique.elections.state.) %>% 
  rename(year = 'ds_years.X1996.2018', state = 'ds_states.unique.elections.state.') %>%
  left_join(elections,by = c('year','state')) %>% 
  arrange(state) %>% na.locf() %>% 
  group_by(state) %>% mutate(party=lag(party)) %>% ungroup() %>% 
  right_join(join_3, by=c('year'='Year','state'='State')) %>%
  mutate(prev_party=party,gdp=GDP,unemp=Unemployment,reg=Region,div=Division,pop_est=PopEst) %>%
  dplyr::select(-c(party,GDP,Unemployment,Region,Division,PopEst))
```

```{r, echo=FALSE, fig.cap="Relationships between pairs of variables"}
gg <- ggpairs(data = ds_final, 
              columns = c("year", "gdp_per_capita", "prev_party", "unemp", "reg"))
gg
```

```{r, echo=FALSE, fig.width=12, fig.cap= "Distribution of GDP per Capita of Democrats and Republicans"}
dens <- ds_final %>% na.omit(prev_party)
ggplot(data=dens,aes(x=gdp_per_capita, fill = prev_party)) + 
  geom_histogram() +
  xlab("GDP per Capita") + ylab("Frequency") 
```

```{r, echo=FALSE, fig.width=12, fig.cap="GDP per Capita of Divisions over the Years for Democrats (Top) and Republicans (Bottom)"}
dem <- ds_final %>% filter(prev_party=="D")
demBox <- ggplot(data=dem,aes(gdp_per_capita,div)) +
  geom_boxplot()+ xlab("GDP per Capita") + 
  ylab("Division") 

rep <- ds_final %>% filter(prev_party=="R")
repBox <- ggplot(data=ds_final, aes(gdp_per_capita,div)) + 
  geom_boxplot() +xlab("GDP per Capita") + 
  ylab("Division")

grid.arrange(demBox, repBox, ncol = 1)
```

```{r, echo = FALSE, fig.cap = "GDP per Capita over the Years of the Divisions and their Parties", fig.width=12}
ggplot(ds_final,aes(x=year,y=gdp_per_capita,color=prev_party)) + 
  geom_point() +  geom_smooth(method="lm",color="black") +
  facet_wrap(~div,ncol=3) +   
  theme(strip.text.x=element_blank())  +
  labs(x="Year",y="GDP per Capita")
```

```{r, echo = FALSE, fig.cap = "GDP per Capita over the Years of the Divisions at each Quartile of Unemployment", fig.width=12}
sample <- ds_final %>%
  mutate(splitup = paste("Quartile", 
                         as.numeric(cut2(unemp, g=4))))

ggplot(sample,aes(x=year,y=gdp_per_capita)) + 
  geom_line(aes(group=div),color="grey") + 
  geom_smooth(method="loess",color="black",se=FALSE,size=.75) +
  facet_grid(~splitup) +
  labs(x="Year",y="GDP per Capita") 
```
